// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADpt9Z6EILlInqKbJzLXa4yAU9j7kBbrQ',
    appId: '1:853976651603:android:ab0cfdebc537a7320173a6',
    messagingSenderId: '853976651603',
    projectId: 'furniture-459cd',
    storageBucket: 'furniture-459cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr3NF_D8fckLpUCWFOuSe4i-j-zUfEo_w',
    appId: '1:853976651603:ios:2c9583f5aa7954340173a6',
    messagingSenderId: '853976651603',
    projectId: 'furniture-459cd',
    storageBucket: 'furniture-459cd.firebasestorage.app',
    androidClientId: '853976651603-406b1a14pake8raftkcilj0u8n7iom7a.apps.googleusercontent.com',
    iosClientId: '853976651603-v5n5fjkea0uh08j43k5955vhj5c42jha.apps.googleusercontent.com',
    iosBundleId: 'com.example.furniture',
  );

}